### PR TITLE
Adds the navbar height as an offset to the target elements in the smoothscroll script. Closes #4.

### LINKED ISSUE #4: Navbar scrolling off by a few pixels
When the navigation sections are clicked on from the top menu, it scrolls and cuts off part of the section title.

### PR DESCRIPTION
**Pull request by lettier**
nyhaskelloffset

Smoothscroll does not account for the nav-bar height (~70px). This adds the nav-bar height `$(".container")[0].clientHeight` to each target's offset.

Closes #4.

### CODE REVIEW

**Comment by katychuang** [comment]
I tried viewing these changes on OSX Chrome and it still looks like there's some offset problems. Which browser/os did you test this on?

**Comment by katychuang** [comment]
I think the change you want is in `_layouts/default.html`, editing the body tag's data-offset attribute

```
<body data-spy="scroll" data-offset="70" data-target="#navbar-main">
```

**Comment by lettier** [comment]
Hi @katychuang. Thank you for reviewing my pull request.

I suspect that you are not downloading my patched `smootherscroll.js` when you click on the navigation links. The navigation bar links are prefixed with the `site.url` found in the [_config.yml](https://github.com/ny-haskell/ny-haskell.org/blob/gh-pages/_config.yml#L13) file.
Before viewing a local build, the `site.url` will need to be set to `http://localhost:4000` (Jekyll's default) for example. Otherwise, the navigation links will take the browser to [ny-haskell.org](http://ny-haskell.org/) requesting the broken `smoothscroll.js` script instead of staying on localhost and just navigating to the URL fragment.

I tested the change on:
- Mac OS X El Capitan Safari
- Mac OS X El Capitan Firefox
- Mac OS X El Capitan Chrome
- iOS 8 Safari
- Android 4 Chrome
- Android 4 Firefox
- Arch Linux Chrome
- Arch Linux Firefox
- Arch Linux Vivaldi

All checks performed correctly.

My procedure was:
- Change the site url to `http://0.0.0.0:4000`
- `$ jekyll serve --watch --host 0.0.0.0`
- Load the site on each device at `http://<internal network ip>:4000`

I didn't see the `data-offset` [documented](http://www.dwuser.com/education/content/quick-guide-adding-smooth-scrolling-to-your-webpages/) anywhere nor is the tag attribute referenced in the minified script.

Still, I did comment out my change and updated the data-offset. The incorrect behavior was still present.

selection_728
selection_727

Thanks! :+1:

**Comment by katychuang** [comment]
Thanks for writing that up!

**Pull request merged**
